### ISSUE TITLE
Upgrade from 3.4 to 4.0

### ISSUE THREAD

**Issue by average-joe** [dj-wasabi/ansible-zabbix-web#34]
**Describe the bug**

I'm trying to upgrade my current zabbix server from 3.4.11 to 4.0. When using this role, I notice the following task doesn't upgrade my zabbix-web-mysql package:

```
- name: "RedHat | Install zabbix-web-{{ zabbix_server_database }}"
  yum:
    pkg: zabbix-web-{{ zabbix_server_database }}
    state: present
  tags:
    - zabbix-web
```

As a result, zabbix server service successfully starts, but there becomes a database error.  Specifically, from the WebUI you get `The frontend does not match Zabbix database`.  

**Installation method/version**

* Github / Master

**Ansible Version**
* ansible version 2.7

**Targetted hosts**
Concerns the following OS(es):

* CentOS

**Expected behavior**

At the completion of the role, zabbix server should successfully be able to access database.  

**Additional context**

To validate, after manually installing the latest zabbix-web-mysql package, I'm successfully able to access Zabbix Web UI.
