### ISSUE TITLE
Apache 2 

### ISSUE THREAD

**Issue by matthew-williams** [dj-wasabi/ansible-zabbix-web#48]
**Describe the bug**
When everything completes, ansible playbook script is successful, it appears that the apache.conf file is not placed correctly inside the conf-enabled folder. When we copy the apache.conf from /etc/zabbix to /etc/apache2/conf-enabled it functions correctly. Version 1.3 worked correctly and it looks like the commit on Feb 02, 2019 broke this.

I understand that the zabbix.conf file in the sites-enabled directory is supposed to make it function, but from what I can tell that file does nothing...not sure why.

**Installation method/version**
Latest version as of 02/25/2019

* Github / latest
* Ansible Galaxy / 1.1.0

**Ansible Version**

```
ansible 2.5.1
  config file = /home/adminlocal/zabbix-server.playbook/ansible.cfg
  configured module search path = [u'/home/adminlocal/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```

**Targetted hosts**
Concerns the following OS(es):

* Ubuntu 16.04.6

**Expected behavior**
Install Zabbix with Apache, PGSQL and an agent installed on target

**Additional context**
***Web Error:***
```
Not Found
The requested URL /zabbix was not found on this server.

Apache/2.4.18 (Ubuntu) Server at 192.168.122.209 Port 80
```
***Ansible Playbook***

```
- hosts: zabbix-server
  become: yes
  roles:
    - { role: postgresql}
    - { role: apache }
    - { role: zabbix-server, zabbix_server_database_type: pgsql, zabbix_server_database_type_long: postgresql, zabbix_server_dbport: 5432 }
    - { role: zabbix-web, zabbix_url: superserver.secmet.co, zabbix_server_database_type: pgsql, zabbix_server_database_type_long: postgresql, zabbix_server_dbport: 5432, zabbix_timezone: America/Denver}
    - { role: zabbix-agent, zabbix_agent_become_on_localhost: False}
```
