### ISSUE TITLE
Dry-run

### ISSUE THREAD

**Issue by vitalijsvolodenkovs** [dj-wasabi/ansible-zabbix-web#50]
I think you should add check mode option for this step:
dj-wasabi.zabbix-web : Get Apache version

At present during dry run we get:
TASK [dj-wasabi.zabbix-web : Get Apache version] *******************************
skipping: [opsv0011]
TASK [dj-wasabi.zabbix-web : Set correct apache_version] ***********************
fatal: [opsv0011]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/var/lib/awx/projects/_21__common_master104645/roles/dj-wasabi.zabbix-web/tasks/main.yml': line 20, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Set correct apache_version\"\n  ^ here\n"}

Check this out: https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html

**Comment by dj-wasabi** [comment]
Hi @vitalijsvolodenkovs 

There is a PR provided by @wschaft , is there a way you can test this before I accept and merge it?

**Comment by vitalijsvolodenkovs** [comment]
Hi, I have already tested in my env:
Changes:
```yaml
- name: "Get Apache version"
  shell: apachectl -v | grep 'version' | awk -F '/' '{ print $2 }'| awk '{ print $1 }' | cut -c 1-3
  changed_when: False
  register: apachectl_version
  check_mode: no
  tags:
    - zabbix-web
```
